Completed Requirements
samdroid-apps/reddit-is-gtk pull request #54
Opened 2016-10-31 15:04 UTC by harishr1308

Autogen.sh runs successfully

2016-11-01 09:25 UTC, Dragnucs commented on README.md
> +4.  Install a SCSS compiler (eg. `rubygem-sass` on Fedora).  This is very
Other SCSS compilers do work. Please do not recommend a tool that needs installing additional dependencies.

2016-11-01 10:16 UTC, samdroid-apps requested changes
Thanks for the contribution!  Feel free to ask questions if you have any more.  Sorry that I went head-first into the re-write without updating these docs.

2016-11-01 10:16 UTC, samdroid-apps commented on README.md
>  2.  Install the `python3-arrow`  and `python3-markdown`
While we are updating the deps, this should no longer be needed (the app is now in vala)

2016-11-01 10:16 UTC, samdroid-apps commented on README.md
> +3.  Install `libglib2.0-dev`,`libgtk-3-dev`,`libsoup2.4-dev`,`libjson-glib-dev`
-dev is the debian name, -devel is the fedora name.  Maybe just keep it distro agnostic and only put the library names there.

2016-11-01 10:16 UTC, samdroid-apps commented on README.md
> +    For Ubuntu run the following commands :
Can we move the distro specific stuff to the end?

2016-11-01 10:16 UTC, samdroid-apps commented on README.md
> +Installing libglib2.0_50
Wow, this is a hard way to do it.  Right now, I'm just using GNOME's `jhbuild` tool to install everything.  It might help you too!

2016-11-01 10:18 UTC, harishr1308 commented on README.md
> +    For Ubuntu run the following commands :
Yea sure go ahead

2016-11-01 10:18 UTC, harishr1308 commented on README.md
> +Installing libglib2.0_50
oh great that simplifies stuff on my end as well

2018-11-19 01:43 UTC, samdroid-apps commented
I think this is no longer needed as we went back to python.  Feel free to test and tell me if there are still issues!  Closing this PR right now thought.

2018-11-19 01:43 UTC, closed without merging